name: Build Flutter AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # جاوا 17 کا سیٹ اپ (چونکہ آپ کے گریڈل میں جاوا 17 سیٹ ہے، یہ بہت ضروری ہے)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          # یہاں ہم نے آپ کے سیکرٹس کے مطابق بالکل درست نام سیٹ کر دیے ہیں
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties
          
          # فائل کو دونوں جگہ کاپی کر رہے ہیں تاکہ پاتھ کا کوئی رولہ نہ رہے
          cp android/key.properties android/app/key.properties

      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
