name: Build Flutter AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.4.4'

      - run: flutter pub get

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/app/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/app/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/app/key.properties
          echo "storeFile=upload-keystore.jks" >> android/app/key.properties

      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
